### ISSUE TITLE
Licence ?

### ISSUE THREAD

**Issue by ncclementi** [necaris/pythonlab-classes#11]
Hey guys all these materials look awesome! I know it is open to the public, but would you add a licence to the repo, so the people that take some material know under what conditions and what they can do with it?

If you want to make it open with no restrictions I would recommend BSD 3-Clause License, but is up to you.  In case you want to explore more about the options (probably you already know them) [here](http://journals.plos.org/ploscompbiol/article/file?id=10.1371/journal.pcbi.1002598&type=printable) is a link to a pretty good paper that is a quick guide to software licencing. I specially like the figure on page 4 that basically summarizes all the possibilities you have.

Anyways, thanks for putting all these together!

**Comment by necaris** [comment]
Thank you @ncclementi for raising the concern! I'm personally a fan of https://opensource.org/licenses (and https://tldrlegal.com/) for license explanations, too. 

I'm going to suggest putting this code under the [GPLv3](https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)), which is a strong copyleft license -- my goal being to ensure that all this code (and derivatives) remain available for educational purposes. Any thoughts / objections? @ndanielsen @ayota @kmb232 @ahlusar1989

**Comment by ndanielsen** [comment]
Sounds about right to me

**Comment by ahlusar1989** [comment]
I am in agreement with @necaris.
